// Dữ liệu phim tập trung cho toàn bộ trang web Netflix (VI/EN)
const listFilm = [
    {
        id: 'marvel',
        titleVi: 'Avengers: Endgame',
        titleEn: 'Avengers: Endgame',
        descVi: 'Avengers: Hồi kết là phim điện ảnh siêu anh hùng Mỹ ra mắt năm 2019. Biệt đội Avengers tập hợp lần cuối để chiến đấu chống lại Thanos nhằm cứu sống một nửa sinh linh trong vũ trụ.',
        descEn: 'After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more to reverse Thanos actions and restore balance.',
        type: 'movie',
        categoryVi: 'Siêu anh hùng',
        categoryEn: 'Superhero',
        year: 2019,
        views: '2.8M',
        rating: 9.2,
        duration: '181 phút',
        castVi: 'Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson',
        castEn: 'Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson',
        director: 'Anthony Russo, Joe Russo',
        videoUrl: 'https://www.youtube.com/embed/TcMBFSGVi1c',
        localVideo: '../assets/video.mp4',
        bannerImg: '../assets/marvel.jpg',
        thumbImg: '../assets/marvel.jpg'
    },
    {
        id: 'dragonball',
        titleVi: 'Dragon Ball Super: Broly',
        titleEn: 'Dragon Ball Super: Broly',
        descVi: 'Trận chiến đỉnh cao giữa Goku, Vegeta và Broly — một chiến binh Saiyan huyền thoại có sức mạnh đáng kinh ngạc. Một cuộc đối đầu kinh thiên động địa sẽ rung chuyển toàn vũ trụ.',
        descEn: 'Goku and Vegeta encounter Broly, a Saiyan warrior unlike any fighter they have faced before. A legendary battle begins that will shake the cosmos.',
        type: 'movie',
        categoryVi: 'Hoạt hình',
        categoryEn: 'Anime',
        year: 2018,
        views: '2.4M',
        rating: 8.7,
        duration: '100 phút',
        castVi: 'Masako Nozawa, Ryo Horikawa, Bin Shimada, Ryusei Nakao',
        castEn: 'Masako Nozawa, Ryo Horikawa, Bin Shimada, Ryusei Nakao',
        director: 'Tatsuya Nagamine',
        videoUrl: 'https://www.youtube.com/embed/wuIbeQv3v7c',
        localVideo: '../assets/video.mp4',
        bannerImg: '../assets/dragonball.jpg',
        thumbImg: '../assets/dragonball.jpg'
    },
    {
        id: 'naruto',
        titleVi: 'Naruto Shippuden',
        titleEn: 'Naruto Shippuden',
        descVi: 'Cuộc chiến cuối cùng của thế giới ninja. Naruto Uzumaki và những người bạn phải hợp sức chống lại thế lực Akatsuki và ngăn chặn âm mưu diệt vong của Uchiha Madara.',
        descEn: 'Naruto Uzumaki, a mischievous adolescent ninja, struggles as he searches for recognition and dreams of becoming the Hokage, the leader of his village.',
        type: 'tv',
        categoryVi: 'Hoạt hình',
        categoryEn: 'Anime',
        year: 2017,
        views: '4.1M',
        rating: 8.9,
        duration: '500 tập',
        castVi: 'Junko Takeuchi, Noriaki Sugiyama, Chie Nakamura, Kazuhiko Inoue',
        castEn: 'Junko Takeuchi, Noriaki Sugiyama, Chie Nakamura, Kazuhiko Inoue',
        director: 'Hayato Date',
        videoUrl: 'https://www.youtube.com/embed/SwgZB2VzxXE',
        localVideo: '../assets/video.mp4',
        bannerImg: '../assets/naruto.jpg',
        thumbImg: '../assets/naruto.jpg'
    },
    {
        id: 'tetdianguc',
        titleVi: 'Tết ở làng địa ngục',
        titleEn: 'Hellbound Village',
        descVi: 'Bộ phim kinh dị cổ trang Việt Nam xoay quanh những biến cố kỳ lạ và đáng sợ ở làng Địa ngục — nơi ẩn chứa một bí mật đẫm máu của một băng cướp khét tiếng qua nhiều thế hệ.',
        descEn: 'A Vietnamese historical horror movie about a mysterious remote village where descendants of notorious bandits live and face terrifying, bloody curses during Tet holiday.',
        type: 'tv',
        categoryVi: 'Kinh dị',
        categoryEn: 'Horror',
        year: 2023,
        views: '1.9M',
        rating: 8.1,
        duration: '12 tập',
        castVi: 'Quang Tuấn, Lan Phương, NSND Ngọc Thư, Nguyên Thảo, Võ Tấn Phát',
        castEn: 'Quang Tuan, Lan Phuong, Ngoc Thu, Nguyen Thao, Vo Tan Phat',
        director: 'Trần Hữu Tấn',
        videoUrl: 'https://www.youtube.com/embed/C2V38ghWHlQ',
        localVideo: '../assets/video.mp4',
        bannerImg: '../assets/tetdianguc.jpg',
        thumbImg: '../assets/tetdianguc.jpg'
    },
    {
        id: 'mufasa',
        titleVi: 'Mufasa: Vua Sư Tử',
        titleEn: 'Mufasa: The Lion King',
        descVi: 'Câu chuyện về hành trình trưởng thành đầy thử thách của Mufasa — từ một chú sư tử mồ côi đơn độc trở thành một vị vua vĩ đại và đáng kính nhất của vùng đất Pride Lands.',
        descEn: 'Mufasa: The Lion King enlists Rafiki to relay the legend of Mufasa to young lion cub Kiara, daughter of Simba and Nala, with Timon and Pumbaa lending their signature schtick.',
        type: 'movie',
        categoryVi: 'Phim Gia đình',
        categoryEn: 'Family',
        year: 2024,
        views: '1.2M',
        rating: 8.3,
        duration: '118 phút',
        castVi: 'Aaron Pierre, Kelvin Harrison Jr., John Kani, Seth Rogen, Billy Eichner',
        castEn: 'Aaron Pierre, Kelvin Harrison Jr., John Kani, Seth Rogen, Billy Eichner',
        director: 'Barry Jenkins',
        videoUrl: 'https://www.youtube.com/embed/TcMBFSGVi1c',
        localVideo: '../assets/video.mp4',
        bannerImg: '../assets/mufasa.jpg',
        thumbImg: '../assets/mufasa.jpg'
    },
    {
        id: 'spiderman',
        titleVi: 'Spider-Man: Không còn đường về',
        titleEn: 'Spider-Man: No Way Home',
        descVi: 'Peter Parker đối mặt với khủng hoảng đa vũ trụ sau khi danh tính Spider-Man bị Mysterio tiết lộ. Những kẻ thù nguy hiểm từ các vũ trụ khác bắt đầu xâm nhập thế giới của anh.',
        descEn: 'With Spider-Mans identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.',
        type: 'movie',
        categoryVi: 'Siêu anh hùng',
        categoryEn: 'Superhero',
        year: 2021,
        views: '3.5M',
        rating: 9.0,
        duration: '148 phút',
        castVi: 'Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon, Jon Favreau',
        castEn: 'Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon, Jon Favreau',
        director: 'Jon Watts',
        videoUrl: 'https://www.youtube.com/embed/TcMBFSGVi1c',
        localVideo: '../assets/video.mp4',
        bannerImg: '../assets/spiderman.jpg',
        thumbImg: '../assets/spiderman.jpg'
    },
    {
        id: 'powerrangers',
        titleVi: 'Năm anh em siêu nhân',
        titleEn: 'Power Rangers',
        descVi: 'Năm chiến binh trẻ tuổi được lựa chọn đặc biệt để chống lại phù thủy hắc ám Rita Repulsa và Lord Zedd khi chúng quay lại nhằm hủy diệt Trái Đất.',
        descEn: 'A group of high-school kids, who are infused with unique superpowers, harness their abilities in order to save the world from an alien threat.',
        type: 'movie',
        categoryVi: 'Siêu nhân',
        categoryEn: 'Sci-fi & Action',
        year: 2017,
        views: '1.5M',
        rating: 7.9,
        duration: '124 phút',
        castVi: 'Dacre Montgomery, Naomi Scott, RJ Cyler, Ludi Lin, Becky G',
        castEn: 'Dacre Montgomery, Naomi Scott, RJ Cyler, Ludi Lin, Becky G',
        director: 'Dean Israelite',
        videoUrl: 'https://www.youtube.com/embed/ZEXfH4Jd8BI',
        localVideo: '../assets/video.mp4',
        bannerImg: '../assets/gái_xinh.jpg',
        thumbImg: '../assets/gái_xinh.jpg'
    }
];

// Xuất biến để sử dụng (hỗ trợ cả NodeJS/ES6 hoặc trình duyệt nhúng)
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { listFilm };
}
